# Generated by Django 4.2 on 2024-03-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customadmin',
            name='is_custom_admin',
        ),
    ]
